CREATE DATABASE IF NOT EXISTS notificaciones_db;
CREATE DATABASE IF NOT EXISTS producto_db;
CREATE DATABASE IF NOT EXISTS pago_db;
CREATE DATABASE IF NOT EXISTS categoria_db;
CREATE DATABASE IF NOT EXISTS calificar_db;
CREATE DATABASE IF NOT EXISTS entrega_db;