spring.application.name=Gateway
server.port=8090

spring.cloud.gateway.routes[0].id=notificaciones
spring.cloud.gateway.routes[0].uri=${NOTIFICACIONES_URL:http://localhost:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/notificacion/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=producto
spring.cloud.gateway.routes[1].uri=${PRODUCTO_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/producto/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=pago
spring.cloud.gateway.routes[2].uri=${PAGO_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pago/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=categoria
spring.cloud.gateway.routes[3].uri=${CATEGORIA_URL:http://localhost:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/categoria/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].id=calificar
spring.cloud.gateway.routes[4].uri=${CALIFICAR_URL:http://localhost:8084}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/calificacion/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].id=entrega
spring.cloud.gateway.routes[5].uri=${ENTREGA_URL:http://localhost:8085}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/entrega/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[6].id=carrito
spring.cloud.gateway.routes[6].uri=${CARRITO_URL:http://localhost:8086}
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/carrito/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[7].id=pedido
spring.cloud.gateway.routes[7].uri=${PEDIDO_URL:http://localhost:8087}
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/pedido/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[8].id=registro
spring.cloud.gateway.routes[8].uri=${REGISTRO_URL:http://localhost:8088}
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/registro/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[9].id=autenticacion
spring.cloud.gateway.routes[9].uri=${AUTENTICACION_URL:http://localhost:8089}
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=1

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
